config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :portfolios do
    # collection do
      # put "welcome"
    # end
    member do
      get :chats
    end
    resources :reviews, only: :create
    resources :designs, only: [ :index, :new, :create ]
    resources :orders, only: [ :new, :create ]
    resources :followers, only: [ :new, :create ]
  end
  resources :designs, only: [ :show, :edit, :update, :destroy ] do
    member do
      patch "upvote", to: "designs#upvote" # likes
    end
  end
  get 'technologies/:technology', to: 'portfolios#index', as: :technology
  get 'filter/:filter', to: 'portfolios#index', as: :filter

  resources :reviews, only: [ :destroy ]
  put '/portfolio/:id/follow', to: 'portfolios#follow', as: 'follow' #seguidores
  put 'is_portfolio', to: 'portfolios#is_portfolio', as: 'is_portfolio'
  get 'welcome', to: 'portfolios#welcome', as: 'welcome'
  resources :orders, only: [ :index, :show, :edit, :update, :destroy ]
  resources :followers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :chatrooms, only: [ :index, :show ] do
    resources :messages, only: :create
  end
  post 'has_chat', to: 'portfolios#has_chat'
  # resources :technologies, only: [ :new, :create ]
  # resources :designs_technologies, only: [ :index, :new, :create ]
end

app/models/design.rb
# == Schema Information
#
# Table name: designs
#
#  id           :bigint           not null, primary key
#  portfolio_id :bigint           not null
#  title        :string
#  description  :text
#  likes        :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Design < ApplicationRecord
  belongs_to :portfolio
  has_many :designs_technologies
  has_one_attached :photo

  acts_as_votable # para los me gustas
  default_scope { order("created_at DESC") }
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  def index
    # @portfolio = Portfolio.find(params[:portfolio_id])
    @designs = Design.where(portfolio_id: params[:portfolio_id])
    @portfolio = Portfolio.find(params[:portfolio_id])
    @design = Design.new

    if params[:query].present?
      @designs = @designs.where('title ILIKE ?', "%#{params[:query]}%")
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'designs/list', locals: { designs: @designs }, formats: [:html] }
    end
  end

  # likes
  def upvote
    @design = Design.find(params[:id])
    if current_user.voted_up_on? @design
      @design.unliked_by current_user
      Portfolio.find(@design.portfolio_id).subtracting_like!
    else
      @design.liked_by current_user
      Portfolio.find(@design.portfolio_id).new_like!
    end
    render "portfolios/vote.js.erb"
  end

  def new
    @portfolio = Portfolio.find(params[:portfolio_id])
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)
    @portfolio = Portfolio.find(params[:portfolio_id])
    @design.portfolio = @portfolio
    respond_to do |format|
      if @design.save
        format.html { redirect_to portfolio_designs_path(@portfolio) }
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render portfolio_designs_path(@portfolio) }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  def show
  end

  def edit
    @design = Design.find(params[:id])
  end

  def update
    @design = Design.find(params[:id])
    # if @design.update(params.require(:design).permit(:title, :description))
      # redirect_to portfolio_designs_path(@design.portfolio_id)
    # else
      # render :edit
    # end
    @design.update(params.require(:design).permit(:title, :description, :photo))
    respond_to do |format|
      format.html { redirect_to portfolio_designs_path(@design.portfolio_id) }
      format.text { render partial: 'designs/design', locals: { design: @design }, formats: [:html] }
    end
  end

  def destroy
    @design = Design.find(params[:id])
    @design.destroy
    # redirect_to portfolio_designs_path(@design.portfolio)
    respond_to do |format|
      format.html { redirect_to portfolio_designs_path(@design.portfolio_id) }
      format.text { render partial: 'designs/list', locals: { design: @design }, formats: [:html] }
    end
  end

  private

  def design_params
    params.require(:design).permit(:title, :description, :portfolio_id, :photo)
  end
end

app/views/designs/_design.html.erb
<div id="design-<%= design.id %>"
  class="rounded shadow-sm py-4 px-4 text-center card card-design"
  data-controller="edit-design" data-edit-design-target="card">

  <!--content de edit-->
  <div data-edit-design-target="infos" class="<%= 'd-none' if design.errors.any? %>">
    <div class="text-center">
      <% if design.photo.key %>
        <%= cl_image_tag design.photo.key, crop: :fill, class: 'img-fluid mb-3 shadow-sm' %>
      <% else %>
        <%= image_tag "#{design.image}", class: 'img-fluid mb-3 shadow-sm' %>
      <% end %>
    </div>
    <h6 class="mb-0"><%= design.title %></h6>
    <span style='color: white; font-weight: 200;' class="small"><%= design.description %></span>

    <ul class="mb-0 list-inline mt-3">
      <!--<li class="list-inline-item">
        <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_design_path(design.id) %>
      </li>-->
      <li class="list-inline-item">
        <i class="fas fa-edit" data-action="click->edit-design#displayForm"></i>
      </li>
      <li class="list-inline-item">
        <%= link_to '<i class="fas fa-trash"></i>'.html_safe,
                design_path(design),
                method: :delete,
                remote: true,
                data: { confirm: "Are you sure?", action: "click->delete-design#delete" } %>
        <!--<%= button_to "delete", design, method: :delete, form_class: "inline",
        data: {action: "click->delete-design#delete"}, class: '' %>-->

      </li>
    </ul>
  </div>

  <%= simple_form_for design, html: { class: design.errors.any? ? '' : 'd-none',
  data: { edit_design_target: 'form', action: 'submit->edit-design#update' }
   } do |f| -%>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Update design", class: "btn btn-sm btn-primary btn-block mt-2 button-digi-grafikka" %>
  <% end %>
</div>

app/views/designs/_form.html.erb
<%= simple_form_for([ portfolio, design ],
              data: {
                insert_design_in_list_target: 'form',
                action: 'submit->insert-design-in-list#send'
              }) do |f| %>

    <%= f.input :title, label: 'Título de la imagen:' %>
    <%= f.input :description, label: 'Descripción:' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Guardar", class: "btn btn-sm mt-2 button-digi-grafikka" %>
<% end %>

app/views/designs/_list.html.erb
<div data-search-designs-target="list" style='margin-bottom: 150px;'>
  <p class=" text-muted">
    <% if params[:query].blank? %>
      <%= pluralize designs.count, 'diseños' %> disponibles
    <% else %>
      <%= pluralize designs.count, 'resultados' %> de <code><%= params[:query] %></code>
    <% end %>
  </p>
  <div class="auto-grid-designs"
    data-insert-design-in-list-target="items"
    data-controller="delete-design">
    <% designs.each do |design| %>
      <%= render 'design', design: design %>
    <% end %>
  </div>
</div>

app/views/designs/edit.html.erb
<%= simple_form_for(@design) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Submit Design", class: "btn btn-primary" %>
<% end %>

app/views/designs/index.html.erb
<div class="container-designs-index">
  <div class="container py-4 container-designs-index" data-controller="insert-design-in-list" data-insert-in-list-position-value="beforeend">
    <p>
      <a class="btn button-digi-grafikka btn-sm" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <i class="fas fa-plus"></i>&nbsp;&nbsp;Nuevo
      </a>
    </p>
    <div class="collapse mb-3" id="collapseExample">
      <div class="card card-body">
        <%= render 'form', portfolio: @portfolio, design: @design %>
      </div>
    </div>


    <div data-controller="search-designs">
      <%= form_with url: portfolio_designs_path(@portfolio),
      method: :get, html: { class: 'mb-4', data: { search_designs_target: 'searchForm' } } do |f| %>
        <%= f.text_field :query,
                          class: "form-control",
                          placeholder: 'Buscar diseño',
                          value: params[:query],
                          style: 'background-color: white',
                          data: {
                            search_designs_target: 'searchInput',
                            action: 'keyup->search-designs#update'
                          }
                          %>
      <% end %>

      <%= render 'list', designs: @designs %>
    </div>
  </div>
</div>

app/views/designs/new.html.erb
<h3>Designs#new</h3>
<%= simple_form_for [ @portfolio, @design ] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
<% end %>