config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :portfolios do
    # collection do
      # put "welcome"
    # end
    member do
      get :chats
    end
    resources :reviews, only: :create
    resources :designs, only: [ :index, :new, :create ]
    resources :orders, only: [ :new, :create ]
    resources :followers, only: [ :new, :create ]
  end
  resources :designs, only: [ :show, :edit, :update, :destroy ] do
    member do
      patch "upvote", to: "designs#upvote" # likes
    end
  end
  get 'technologies/:technology', to: 'portfolios#index', as: :technology
  get 'filter/:filter', to: 'portfolios#index', as: :filter

  resources :reviews, only: [ :destroy ]
  put '/portfolio/:id/follow', to: 'portfolios#follow', as: 'follow' #seguidores
  put 'is_portfolio', to: 'portfolios#is_portfolio', as: 'is_portfolio'
  get 'welcome', to: 'portfolios#welcome', as: 'welcome'
  resources :orders, only: [ :index, :show, :edit, :update, :destroy ]
  resources :followers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :chatrooms, only: [ :index, :show ] do
    resources :messages, only: :create
  end
  post 'has_chat', to: 'portfolios#has_chat'
  # resources :technologies, only: [ :new, :create ]
  # resources :designs_technologies, only: [ :index, :new, :create ]
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id            :bigint           not null, primary key
#  user_id       :bigint           not null
#  total_likes   :float
#  stars_average :float
#  about         :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Portfolio < ApplicationRecord
  belongs_to :user
  has_many :followers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :designs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :portfolios_technologies, dependent: :destroy
  has_many :technologies, through: :portfolios_technologies

  # default_scope { order("created_at DESC") }

  def following?(user)
    !!self.followers.find{|follower| follower.user_id == user.id}
  end

  # Adding technologies to every portfolio
  def self.tagged_with(name)
    Technology.find_by_name!(name).portfolios
  end

  def self.tag_counts
    Technology.select('technologies.*, count(portfolios_technologies.technology_id) as count')
       .joins(:portfolios_technologies).group('portfolios_technologies.technology_id')
  end

  def tag_list
    technologies.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.technologies = names.split(',').map do |n|
      Technology.where(name: n.strip).first_or_create!
    end
  end

  def self.sort_portfolios_by(query)
    case query
    when 'Likes ↓'
      Portfolio.order('total_likes DESC')
    when 'Likes ↑'
      Portfolio.order('total_likes ASC')
    when 'Seguidores ↓'
      Portfolio.order('total_followers DESC')
    else
      Portfolio.order('total_followers ASC')
    end
  end

  def new_follower!
    self.update_columns(total_followers: (self.total_followers + 1))
  end

  def subtracting_follower!
    self.update_columns(total_followers: (self.total_followers - 1))
  end

  def new_like!
    self.update_columns(total_likes: (self.total_likes + 1))
  end

  def subtracting_like!
    self.update_columns(total_likes: (self.total_likes - 1))
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[show edit update destroy]

  def follow
    @portfolio = Portfolio.all.find(params[:id])
    if @portfolio.following?(current_user)
      @follower = Follower.where(user_id: current_user.id)
                          .and(Follower.where(portfolio_id: @portfolio.id))
      @portfolio.subtracting_follower!
      @follower[0].destroy
    else
      Follower.create(user_id: current_user.id, portfolio_id: @portfolio.id)
      @portfolio.new_follower!
    end
    redirect_to portfolio_path(@portfolio, anchor: "button-follower")
  end

  def is_portfolio
    @portfolio = Portfolio.find_by(user_id: current_user.id)
    if @portfolio
      redirect_to portfolio_designs_path(@portfolio)
    else
      # redirect_to welcome_portfolios_path
      redirect_to welcome_path
    end
  end

  def has_chat
    @chatroom = Chatroom.where(user_id: current_user.id)
                        .and(Chatroom.where(portfolio_id: params[:portfolio_id])) ||
                Chatroom.where(user_id: params[:portfolio_id])
                        .and(Chatroom.where(portfolio_id: current_user.id))

    if @chatroom.exists?
      redirect_to chatroom_path(@chatroom[0].id)
    else
      @new_chatroom = Chatroom.new(user_id: current_user.id, portfolio_id: params[:portfolio_id])
      @new_chatroom.save
      redirect_to chatroom_path(@new_chatroom)
    end
  end

  def chats
    @chatrooms = Chatroom.where(portfolio_id: params[:id])
    @portfolio = Portfolio.find(params[:id])
  end

  def index
    # if params[:query].present?
    #   @portfolios = policy_scope(Portfolio).where("title ILIKE ?  OR author ILIKE ?", "%#{params[:query]}%","%#{params[:query]}%")
    # # qu epusieron para las busquedas?
    # else
    #   @portfolios = policy_scope(Portfolio).order(created_at: :desc)
    # end
    @technologies = %w[Photoshop InDesign CorelDraw Illustrator Inkscape Sketch Canva Photoscape Otras]
    @filters = ['Likes ↓', 'Seguidores ↓', 'Likes ↑', 'Seguidores ↑']
    return @portfolios = Portfolio.tagged_with(params[:technology]) if params[:technology]
    return @portfolios = Portfolio.sort_portfolios_by(params[:filter]) if params[:filter]

    @portfolios = Portfolio.order("created_at DESC")
  end

  def show
    # aqui deberia verse asip peor ya lo puse en set_portfolio
    # @portfolio = Portfolio.find(params[:id])
    # GEOCODING
    # @latitude_and_longitude = User.geocoded
    # @latitude_and_longitude = User.near(current_user.address, 10)
    # @markers = @latitude_and_longitude.geocoded.map do |user|
    #  {
    #    lat: user.latitude,
    #    lng: user.longitude,
    #    info_window: render_to_string(partial: "info_window", locals: { user: user })
    # }
    # end
    # authorize @portfolio
    # @portfolio = Portfolio.find(params[:id])
    @review = Review.new
  end

  def new
    @portfolio = Portfolio.new
    # authorize @portfolio
  end

  def create
    # @portfolio = current_user.portfolios.new(portfolio_params)
    @portfolio = Portfolio.new(portfolio_params)

    @portfolio.user = current_user
    # authorize @portfolio
    if @portfolio.save
      redirect_to portfolios_path
    else
      render :new
    end
  end

  def edit
    # authorize @portfolio
  end

  def update
    # @portfolio = Portfolio.find(params[:id])
    @portfolio.update(params[:portfolio])
    # authorize @portfolio
    # if @portfolio.update(portfolio_params)
    #   redirect_to portfolio_path(@portfolio)
    # else
    #   render :edit
    # end
  end

  def destroy
    @restaurant.destroy

    # @portfolio = Portfolio.find(params[:id])
    # authorize @portfolio
    # @portfolio.destroy if @portfolio.present?
    # redirect_to portfolios_path
  end

  private

  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(
      :about, :tag_list, :technology, { technology_ids: [] }, :technology_ids,
      :career, :years_of_experience
    )
  end
end

app/views/portfolios/_form.html.erb
<%= simple_form_for(portfolio) do |f| %>
  <div class="form-inputs" style="color:black">
    <div class="mb-3">
      <%= f.input :about, label: 'Agrega una descripción personal para que te conozcan:', style: 'margin-bottom: 15px;' %>
    </div>
    <div class="mb-3">
      <%= f.input :career, label: 'Agrega tus estudios profesionales:' %>
    </div>
    <div class="mb-3">
      <%= f.input :years_of_experience, label: '¿Cuántos años tienes de experiencia?:' %>
    </div>

    <div class="mb-3">
      <%= f.input :technology_ids, as: :select, label: 'Tecnologías:',
            hint: '(Presiona la tecla Ctrl para seleccionar más de una opción)',
            collection: Technology.order(:name), label_method: :name, input_html: { multiple: true } %>
    </div>
  </div>

  <div class="form-actions" style="padding-bottom: 140px;">
    <%= f.submit 'Add portfolio', class: 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/portfolios/_upvote_link.html.erb
<%= content_tag "span", id: "upvote-#{design.id}" do %>
  <%= link_to upvote_design_path(design), method: :patch, remote: true, data: { disable_with: "voting..." }, style: "text-decoration: none;" do %>
    <% if current_user.voted_up_on? design %>
      <i class="fas fa-thumbs-up"></i>
    <% else %>
      <i class="far fa-thumbs-up"></i>
    <% end %>
  <% end %>
<% end %>

app/views/portfolios/_votes_score.html.erb
<%= content_tag "span", id: "votes-score-#{design.id}", style: "font-size: 18px;" do %>
  <%= design.cached_votes_score %>
<% end %>

app/views/portfolios/chats.html.erb
<% if user_signed_in? %>
  <div class="portfolios-container" style='color:red'>
    <div class="container" style='padding-bottom: 20px'>
      <h4 class="" style='color: black; padding-top: 40px'>Conversaciones</h4>
      <div class="container-followers">
        <% @chatrooms.each do |chatroom| %>
          <div class="follower bg-white has-shadow my-3 p-2">
            <span>
              <%= link_to chatroom_path(chatroom) do %>
                <%= image_tag "#{chatroom.portfolio.user.image}", width: 80, class: 'img-fluid rounded-circle img-thumbnail shadow-sm' %>
              <% end %>
            </span>
            <div class="description-follower ms-2">
              <h5 class="m-1">Todo list with React, Redux, TypeScript and drag and drop</h5>
              <p class="text-muted m-0 ps-1"><%= chatroom.user.name %> <%= chatroom.user.last_name %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/destroy.html.erb
<h1>Portfolios#destroy</h1>
<p>Find me in app/views/portfolios/destroy.html.erb</p>
aqui deberia ponerse una alerta

app/views/portfolios/edit.html.erb
<h1 class='book-h1'>Edita tu portafolio</h1>
<br>
<%= link_to 'Regresar', portfolios_path, class: 'portfolio-back' %>
<div class='portfolio-form'>
    <%= render 'form', portfolio: @portfolio %>
</div>

app/views/portfolios/index.html.erb
<div style="background-color: #F1E9E4; margin-top: 20px;" class="pb-3">
  <div class='sort-container' style='margin-bottom: 20px'>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Escoge una tecnología
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li>
            <%= link_to 'Todas', portfolios_path,
              class: "dropdown-item", style: 'display: inline' %>
        </li>
        <% @technologies.each do |technology| %>
          <li>
            <%= link_to technology, technology_path(technology),
              class: "dropdown-item", style: 'display: inline' %>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Ordenar por
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% @filters.each do |filter| %>
          <li>
            <%= link_to filter, filter_path(filter),
              class: "dropdown-item", style: 'display: inline' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="container" style='margin-bottom: 150px'>
    <div class="auto-grid-designs">
      <% @portfolios.each do |portfolio| %>
        <div class="rounded shadow-sm pb-3 card card-index-porfios" style='background-color: rgba(33, 34, 59, 0.9)'>
          <div class="container-designs">
            <% @portfolio1 = portfolio.designs.sample %>
            <% @portfolio2 = portfolio.designs.sample %>
            <% if portfolio.designs.exists? %>
              <% if @portfolio1.photo.key %>
                <div>
                  <%= cl_image_tag @portfolio1.photo.key, crop: :fill %>
                </div>
              <% else %>
                <div>
                  <%= image_tag("#{@portfolio1.image}")  %>
                </div>
              <% end %>

              <% if @portfolio2.photo.key %>
                <div>
                  <%= cl_image_tag @portfolio2.photo.key, crop: :fill %>
                </div>
              <% else %>
                <div>
                  <%= image_tag("#{@portfolio2.image}") %>
                </div>
              <% end %>
            <% else %>
              <div>
                  <%= image_tag("diseno1.jpg") %>
                </div>
                <div>
                  <%= image_tag("diseno2.jpg") %>
                </div>
            <% end %>

          </div>
          <div class="container-tech text-center" style="margin-top: -30px">
            <%= link_to portfolio_path(portfolio) do %>
              <% if portfolio.user.image %>
                <%= image_tag "#{portfolio.user.image}", width: 100, style: 'background-color: #F1E9E4',
                class: 'img-fluid rounded-circle mb-3 img-thumbnail shadow-sm img-user' %>
              <% else %>
                <%= image_tag "avatar.png", width: 100, style: 'background-color: #F1E9E4',
                class: 'img-fluid rounded-circle mb-3 img-thumbnail shadow-sm img-user' %>
              <% end %>
            <% end %>
            <h6 class="mb-0">
              <%= link_to "#{portfolio.user.name} #{portfolio.user.last_name}", portfolio_path(portfolio) %>
            </h6>
            <span style='color: white; font-weight: 200' class="small "><i class="fas fa-map-marker-alt"></i><%= " #{portfolio.user.address}" %></span>

            <div class='index-technologies'>
              <% portfolio.tag_list.split(', ').each do |technology| %>
              <p><%= image_tag("#{technology}-logo.png", style: 'height: 30px') %></p>
            <% end %>
            </div>
          </div>
          <div class="content-favorites-and-likes">
            <div>
              <p class="m-0 text-center"><%= "#{portfolio.total_followers} " %></p>
              <p style="color: white" class="small m-0 text-center">seguidores</p>
            </div>
            <div>
              <p class="m-0 text-center"><%= "#{portfolio.total_likes.round(0)} " %></p>
              <p style="color: white" class="small m-0 text-center">likes</p>
            </div>
          </div>
          <div class="button-card-portfolio mt-4" >
            <p class="text-center mensaje" >
              <% if user_signed_in? %>
                <%= link_to has_chat_path(:portfolio_id => portfolio), method: "post", class: 'portfolios-btn'  do %>
                  <i class="fas fa-envelope"></i></i>&nbsp;&nbsp;Mensaje
                <% end %>
              <% else %>
                <%= link_to user_session_path, class: 'portfolios-btn'  do %>
                  <i class="fas fa-envelope"></i></i>&nbsp;&nbsp;Mensaje
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container mt-5">
  <h4 class='book-h1' style="color:black">Agrega un nuevo portafolio</h4>
  <br>

  <div class='portfolio-form'>
    <%= render 'form', portfolio: @portfolio %>
  </div>
</div>

app/views/portfolios/show.html.erb
<div class="portfolios-container">
  <div class='portfolios-banner'>

    <% if @portfolio.user.image %>
      <%= image_tag "#{@portfolio.user.image}", class: 'portfolios-perfil' %>
    <% else %>
      <%= image_tag "avatar.png", class: 'portfolios-perfil' %>
    <% end %>

    <% if @portfolio.designs.exists? %>
      <% design = @portfolio.designs.sample %>
      <% if design.photo.key %>
        <%= cl_image_tag design.photo.key, crop: :fill, class: 'portfolios-background' %>
      <% else %>
        <%= image_tag("#{design.image}", class: 'portfolios-background') %>
      <% end %>
    <% else %>
      <%= image_tag("background.png", class: 'portfolios-background') %>
    <% end %>


  </div>
  <div class="container">
    <div class='portfolios-details'>
      <p class='designer-name text-center'><%= "#{@portfolio.user.name} #{@portfolio.user.last_name}" %></p>
      <p class='designer-description text-center'>Freelance Brand and Logo Designer</p>
      <p class='designer-location text-center'>📍<%= " #{@portfolio.user.address}" %></p>
      <div class="content-followers-and-likes">
          <div class='followers'>
            <p class="m-0 text-center"><%= "#{@portfolio.total_followers} " %></p>
            <p class="small text-muted m-0 text-center">seguidores</p>
          </div>
          <div class='likes'>
            <p class="m-0 text-center"><%= "#{@portfolio.total_likes.round(0)} " %></p>
            <p class="small text-muted m-0 text-center">likes</p>
          </div>
        </div>
      <div class='buttons-container text-center mb-5' id="button-follower">
        <% if user_signed_in? %>
          <% if current_user == @portfolio.user %>
            <%= link_to 'Mis diseños', portfolio_designs_path(@portfolio), class: 'portfolios-btn' %>
            <%= link_to 'Mi Chat', chatrooms_path, class: 'portfolios-btn' %>
          <% else %>
            <% if @portfolio.following?(current_user) %>
              <%= button_to "Siguiendo", follow_path(@portfolio), method: "put", remote: true, class: 'portfolios-btn' %>
            <% else %>
              <%= button_to "Sígueme", follow_path(@portfolio), method: "put", remote: true, class: 'portfolios-btn' %>
            <% end %>
            <%= link_to 'Contáctame', has_chat_path(:portfolio_id => @portfolio), method: "post", class: 'portfolios-btn' %>
          <% end %>
        <% end %>
      </div>

      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Mis diseños</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Perfil</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Contacto</button>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent" style='padding-bottom: 30px'>
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class='auto-grid-designs'>
            <% @portfolio.designs.each do |design| %>
              <div class="card">
                <div class="img-container img-design" style="">
                  <% if design.photo.key %>
                    <%= cl_image_tag design.photo.key, crop: :fill %>
                  <% else %>
                    <%= image_tag "#{design.image}"%>
                  <% end %>
                </div>
                <div class="card-body">
                  <h5 class="card-title text-center"><%= design.title %></h5>
                  <p class="card-text text-center"><%= design.description %></p>
                  <p class="text-center">
                    <%= render "portfolios/votes_score", design: design, class: 'text-center' %>
                    <% if user_signed_in? %>
                      <%= render "portfolios/upvote_link", design: design, class: 'text-center' %>
                    <% else %>
                      <%= 'Likes' %>
                    <% end %>
                  </p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade sobre-mi" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
          <h4>Sobre mi:</h4>
          <p style='font-size: 18px; text-align: justify'>Se puede decir que soy un tipo que ha
            tenido la suerte de trabajar en lo que le gusta y le apasiona estos últimos 25 años de su vida.
            Soy egresado del Instituto Superior de Comunicación Visual de Rosario con el título
            de Diseñador Gráfico. Realizo cursos, másteres para mejorar mi formación y estar
            permanentemente actualizado en esta profesión tan cambiante. He tenido el privilegio
            de trabajar en empresas de diversos sectores como Parques Reunidos, Lanetro Zed,
            Recoletos Grupo de Comunicación (Unidad Editorial), Publicis Dialog, Ahorro
            Corporación Financiera entre otras. En la actualidad trabajo como freelance para
            clientes que con su confianza en mi trabajo me permiten continuar con mi desarrollo
            profesional.</p>
            <div class='perfil-cards'>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Mi experiencia</h5>
                  <p style='text-align: justify' class="card-text">Grupo Prima / Parques Reunidos / Lanetro Zed / Recoletos Grupo de Comunicación / Publicis Dialog / Ahorro Corporación Financiera / JOT Internet Media. Actualmente trabajo por mi cuenta como diseñador gráfico y web freelance.</p>
                </div>
              </div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Mis conocimientos</h5>
                  <p style='text-align: justify' class="card-text">Photoshop / Illustrator / Dreamweaver / Flash / Fireworks / Indesign / Acrobat / Premiere/ Final Cut / HTML5 / CSS3 / WordPress / nociones de Actionscript, Javascript y PHP entre otros. Trabajo tanto en plataforma MAC (preferentemente) como en PC.</p>
                </div>
              </div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Más información</h5>
                  <p style='text-align: justify' class="card-text">Te invito a descargar mi CV en formato PDF donde encontrarás en detalle toda mi experiencia y mi formación.</p>
                  <button class='mt-5 btn btn-primary'>Descargar CV</button>
                </div>
                </div>
            </div>
          </div>
        <div class="tab-pane fade sobre-mi" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
          <h4>Teléfono:</h4>
          <p style='font-size: 18px'>• <%= @portfolio.user.phone %></p>
          <h4>Correo electrónico:</h4>
          <p style='font-size: 18px'>• <%= @portfolio.user.email %></p>
        </div>
      </div>

    </div>


    <div data-controller="insert-review-in-list" data-insert-in-list-position-value="beforeend">

      <div class='reviews-show mt-5'>
        <br>
        <% if @portfolio.reviews.blank? %>
          <p><i class="far fa-comment-alt"></i>&nbsp; Sé el primero en dejar un comentario</p>
        <% else %>
          <h4 class="mb-3">Comentarios</h4>
          <% @portfolio.reviews.order('created_at DESC').each do |review| %>
            <div class="container-reviews" data-insert-review-in-list-target="items">
              <div class="container-user">
                <div class="content-user">
                  <figure class="m-0">
                    <% if review.user.image %>
                      <%= image_tag "#{review.user.image}", width: 70, height: 70, class: 'img-fluid rounded-circle img-thumbnail shadow-sm img-user' %>
                    <% else %>
                      <%= image_tag "avatar.png", width: 70, height: 70, class: 'img-fluid rounded-circle img-thumbnail shadow-sm img-user' %>
                    <% end %>
                  </figure>
                  <div class="ps-2">
                    <p class="m-0"><%= review.user.name %> <%= review.user.last_name %></p>
                    <p class="small text-muted m-0">
                      <% review.rating.times do  %>
                        <i class="fas fa-star" style='color: #FFCE00'></i>
                      <% end %>
                      <% review.blank_stars.times do %>
                        <i class="far fa-star" style='color: #FFCE00'></i>
                      <% end %> &nbsp;|&nbsp;
                      <%= review.created_at.utc.localtime("-05:00").strftime("%h %d, %Y - %I:%M %p") %>
                    </p>

                    <div class="content-body-review">
                      <div>
                        <h6 style="margin-bottom: 2px;"><%= review.title %></h6>
                        <p><%= review.content %></p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="pe-3">
                  <% if user_signed_in? && review.user == current_user %>
                    <%= link_to review_path(review, :portfolio_id => review.portfolio),
                      method: :delete,
                      class: 'product-remove rounded-circle btn',
                      data: { confirm: "¿Estás seguro?" } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class='review-form' style="padding-bottom: 140px;">
        <% if user_signed_in? %>
            <hr>

            <p class=''>Introduce tu comentario</p>
            <%= simple_form_for([ @portfolio, @review ], remote: true) do |f| %>
              <div class="flex-inputs">
                <%= f.input :title, placeholder: "Titulo", class: "m-2" %>
                <%= f.input :rating, placeholder: "Valoración" %>
              </div>
              <div class="flex-inputs">
                <%= f.input :content, as: :text, placeholder: "Comentario",class: "m-2" %>
              </div>
              <div class='text-right'>
                <%= f.submit 'Agregar Comentario', class: 'btn btn-outline-primary button-digi-grafikka mb-3' %>
              </div>
            <% end %>

        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/portfolios/vote.js.erb
document.getElementById("upvote-<%= @design.id %>").innerHTML = "<%= j render 'portfolios/upvote_link', design: @design %>"
document.getElementById("votes-score-<%= @design.id %>").innerHTML = "<%= j render "portfolios/votes_score", design: @design %>";

app/views/portfolios/welcome.html.erb
<div class="container-welcome">
 <div class="formulario" style= "width:100%; ">
   <%= image_tag("agregarportfolio.png", style:"width:100%; " )%>
     <%= link_to 'Agregar Portafolio', new_portfolio_path, class:'button-card-portfolios' %>
  </div>
</div>