config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :portfolios do
    # collection do
      # put "welcome"
    # end
    member do
      get :chats
    end
    resources :reviews, only: :create
    resources :designs, only: [ :index, :new, :create ]
    resources :orders, only: [ :new, :create ]
    resources :followers, only: [ :new, :create ]
  end
  resources :designs, only: [ :show, :edit, :update, :destroy ] do
    member do
      patch "upvote", to: "designs#upvote" # likes
    end
  end
  get 'technologies/:technology', to: 'portfolios#index', as: :technology
  get 'filter/:filter', to: 'portfolios#index', as: :filter

  resources :reviews, only: [ :destroy ]
  put '/portfolio/:id/follow', to: 'portfolios#follow', as: 'follow' #seguidores
  put 'is_portfolio', to: 'portfolios#is_portfolio', as: 'is_portfolio'
  get 'welcome', to: 'portfolios#welcome', as: 'welcome'
  resources :orders, only: [ :index, :show, :edit, :update, :destroy ]
  resources :followers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :chatrooms, only: [ :index, :show ] do
    resources :messages, only: :create
  end
  post 'has_chat', to: 'portfolios#has_chat'
  # resources :technologies, only: [ :new, :create ]
  # resources :designs_technologies, only: [ :index, :new, :create ]
end

app/models/chatroom.rb
# == Schema Information
#
# Table name: chatrooms
#
#  id           :bigint           not null, primary key
#  portfolio_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Chatroom < ApplicationRecord
  belongs_to :portfolio
  has_many :messages, dependent: :destroy
  belongs_to :user
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.where(portfolio_id: current_user).or(Chatroom.where(user_id: current_user))
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/views/chatrooms/index.html.erb
<div class="portfolios-container" style='padding: 50px 0'>
  <div class="container" style='padding-bottom: 70px'>
    <h4 class="">Conversaciones</h4>
    <div class="container-followers">
      <% @chatrooms.each do |chatroom| %>
        <div class="follower bg-white has-shadow my-3 p-2">
          <span>
            <%= link_to chatroom_path(chatroom) do %>
              <% if chatroom.portfolio.user.image.nil? ||chatroom.portfolio.user.name == current_user.name%>
                 <%= image_tag "avatar.png", width: 80, class: 'img-fluid rounded-circle img-thumbnail shadow-sm' %>
              <% else %>
                <%= image_tag "#{chatroom.portfolio.user.image}", width: 80, class: 'img-fluid rounded-circle img-thumbnail shadow-sm' %>
              <% end %>
            <% end %>
          </span>
          <div class="description-follower ms-2">
            <% if chatroom.portfolio.user.name == current_user.name %>
            <h5 class="m-1"><%= chatroom.user.name %> <%= chatroom.user.last_name %></h5>
            <p class="text-muted m-0 ps-1"><%= chatroom.user.email %></p>
            <% else %>
            <h5 class="m-1"><%= chatroom.portfolio.user.name %> <%= chatroom.portfolio.user.last_name %></h5>
            <p class="text-muted m-0 ps-1"><%= chatroom.portfolio.user.email %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<% if user_signed_in? %>
  <% if current_user.id == @chatroom.user_id || @chatroom.portfolio_id == current_user.portfolio.id %>
  <div class="messages-container" style='padding-bottom: 150px'>
    <div class="container">
      <h1 style='margin: 30px 0px; text-align: center'>Chat con
      <% if @chatroom.portfolio.user.name == current_user.name %>
      <%= @chatroom.user.name %></h1>
      <% else %>
        <%= @chatroom.portfolio.user.name %></h1>
      <% end %>
      <div style='margin-bottom: 30px ' id="messages" data-chatroom-id="<%= @chatroom.id %>">
        <% @chatroom.messages.each do |message| %>
          <%= render 'messages/message', message: message %>
        <% end %>
      </div>

      <%= simple_form_for [ @chatroom, @message ],
      remote: true, html: {class: 'input-message'} do |f| %>
        <%= f.input :content, label: false, placeholder: "Escribe tu mensaje" %>
      <% end %>
    </div>
  </div>
  <% end %>
<% end %>