config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :portfolios do
    # collection do
      # put "welcome"
    # end
    member do
      get :chats
    end
    resources :reviews, only: :create
    resources :designs, only: [ :index, :new, :create ]
    resources :orders, only: [ :new, :create ]
    resources :followers, only: [ :new, :create ]
  end
  resources :designs, only: [ :show, :edit, :update, :destroy ] do
    member do
      patch "upvote", to: "designs#upvote" # likes
    end
  end
  get 'technologies/:technology', to: 'portfolios#index', as: :technology
  get 'filter/:filter', to: 'portfolios#index', as: :filter

  resources :reviews, only: [ :destroy ]
  put '/portfolio/:id/follow', to: 'portfolios#follow', as: 'follow' #seguidores
  put 'is_portfolio', to: 'portfolios#is_portfolio', as: 'is_portfolio'
  get 'welcome', to: 'portfolios#welcome', as: 'welcome'
  resources :orders, only: [ :index, :show, :edit, :update, :destroy ]
  resources :followers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :chatrooms, only: [ :index, :show ] do
    resources :messages, only: :create
  end
  post 'has_chat', to: 'portfolios#has_chat'
  # resources :technologies, only: [ :new, :create ]
  # resources :designs_technologies, only: [ :index, :new, :create ]
end

app/views/shared/_flashes.html.erb
<% if notice %>
 <div class="alert alert-success alert-dismissible fade show" role="alert">
  🎉 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    😱 <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Creado por &nbsp;<i class="fas fa-heart"></i>&nbsp; Digi Grafikka
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background: #21223B; -webkit-box-shadow: 0 2px 4px 0 rgb(0 0 0 / 25%);
    box-shadow: 0 2px 4px 0 rgb(0 0 0 / 25%);">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">DIGI GRAFIKKA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Diseñadores', portfolios_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Compartir tu trabajo', is_portfolio_path, method: "put", remote: true, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mis Seguidores', followers_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mi Chat', chatrooms_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
        <% if user_signed_in? %>
          <li class="nav-item dropdown", style='list-style-type: none;'>
            <% if current_user.image.nil? %>
              <%= image_tag "avatar.png", class: "avatar-nav dropdown-toggle", id: "navbarDropdown",
              data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style: 'background-color: black' %>
            <% else %>
              <%= image_tag "#{current_user.image}", class: "avatar-nav dropdown-toggle",
                id: "navbarDropdown", data: { bs_toggle: "dropdown" },
                'aria-haspopup': true, 'aria-expanded': false, style: 'background-color: white' %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi cuenta", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.portfolio %>
                <%= link_to "Mi perfil", portfolio_path(current_user.portfolio), class: "dropdown-item" %>
              <% end %>
             <%#<%= link_to "Mi cuenta", portfolio_path(current_user.portfolio), class: "dropdown-item" %>
              <%= link_to "Editar cuenta", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Mis seguidores", followers_path, class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item position-absolute top-50 end-0 translate-middle-y login ", style='list-style-type: none;'>
            <%= link_to 'Iniciar sesión', user_session_path, class: 'btn btn-login-digigraffika' %>
          </li>
        <% end %>



    </div>
  </div>
</nav>